const fs = require('fs');
let code = fs.readFileSync('src/pages/Settings.tsx', 'utf8');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.tagline1 \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, tagline1: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.tagline1} value={content.tagline1 || \'\'} onChange={(e) => setContent({...content, tagline1: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.tagline2 \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, tagline2: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.tagline2} value={content.tagline2 || \'\'} onChange={(e) => setContent({...content, tagline2: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<textarea\n\s*rows=\{3\}\n\s*value=\{content\.description \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, description: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<textarea rows={3} placeholder={DEFAULT_CONTENT.description} value={content.description || \'\'} onChange={(e) => setContent({...content, description: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.admissionsBadge \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, admissionsBadge: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.admissionsBadge} value={content.admissionsBadge || \'\'} onChange={(e) => setContent({...content, admissionsBadge: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<textarea\n\s*rows=\{4\}\n\s*value=\{content\.principalMessage \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, principalMessage: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<textarea rows={4} placeholder={DEFAULT_CONTENT.principalMessage} value={content.principalMessage || \'\'} onChange={(e) => setContent({...content, principalMessage: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.statsStudents \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, statsStudents: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.statsStudents} value={content.statsStudents || \'\'} onChange={(e) => setContent({...content, statsStudents: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.statsTeachers \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, statsTeachers: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.statsTeachers} value={content.statsTeachers || \'\'} onChange={(e) => setContent({...content, statsTeachers: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.statsPassRate \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, statsPassRate: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.statsPassRate} value={content.statsPassRate || \'\'} onChange={(e) => setContent({...content, statsPassRate: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

code = code.replace(/<input\n\s*type="text"\n\s*value=\{content\.contactPhone \|\| ''\}\n\s*onChange=\{\(e\) => setContent\(\{\.\.\.content, contactPhone: e\.target\.value\}\)\}\n\s*className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-\[var\(--primary\)\] px-3 py-2 text-sm font-medium"/g, 
  '<input type="text" placeholder={DEFAULT_CONTENT.contactPhone} value={content.contactPhone || \'\'} onChange={(e) => setContent({...content, contactPhone: e.target.value})} className="w-full border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] px-3 py-2 text-sm font-medium placeholder:text-gray-400 placeholder:opacity-75"');

fs.writeFileSync('src/pages/Settings.tsx', code);
